stages:
  - test
  - build
  - deploy

test:
  image: python:3.9
  stage: test

  services:
    - postgres

  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /hotfix/

  variables:
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv
    PIP_DOWNLOAD_CACHE: $CI_PROJECT_DIR/.cache/pip_download_cache
    ENV_FOR_DYNACONF: test

  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .cache

  coverage: '/TOTAL.*\s+(\d+%)$/'

  before_script:
    - pip install .[test]

  script:
    #  - pip install black --upgrade
    #  - python -m unittest -v
    - coverage run -m pytest
    #  - black -S -l 80 --check --diff ./
    - coverage report -m --skip-covered
